webtalk_init -webtalk_dir C:/Users/AhmedAli/Desktop/CA Project/Vivado Project Files/Pipelined_Processor/Pipelined_Processor.sim/sim_1/behav/xsim/xsim.dir/TB_Pipelined_Processor_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu May 11 14:29:35 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "a1f31ffb-b68b-4d9e-bcfd-0c8c45484ea4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "115a1077c7e14f93aae906ca039b1f82" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 3450U with Radeon Vega Mobile Gfx  " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2096 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "6.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "25 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8616_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2694833504 -regid "" -xml C:/Users/AhmedAli/Desktop/CA Project/Vivado Project Files/Pipelined_Processor/Pipelined_Processor.sim/sim_1/behav/xsim/xsim.dir/TB_Pipelined_Processor_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/AhmedAli/Desktop/CA Project/Vivado Project Files/Pipelined_Processor/Pipelined_Processor.sim/sim_1/behav/xsim/xsim.dir/TB_Pipelined_Processor_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/AhmedAli/Desktop/CA Project/Vivado Project Files/Pipelined_Processor/Pipelined_Processor.sim/sim_1/behav/xsim/xsim.dir/TB_Pipelined_Processor_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
